name: commandrecognition
channels:
  - plotly
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - appdirs=1.4.4
  - audioread=3.0.0
  - blas=1.0
  - boost-cpp=1.73.0
  - bottleneck=1.3.5
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2022.12.7
  - cairo=1.16.0
  - certifi=2022.12.7
  - cffi=1.15.1
  - charset-normalizer=2.1.1
  - click=8.0.4
  - colorama=0.4.6
  - commonmark=0.9.1
  - contourpy=1.0.5
  - cryptography=38.0.4
  - cudatoolkit=11.2.2
  - cudnn=8.1.0.77
  - cycler=0.11.0
  - dataclasses=0.8
  - decorator=5.1.1
  - expat=2.4.9
  - flit-core=3.6.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=2.001
  - font-ttf-source-code-pro=2.030
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.1
  - fonts-anaconda=1
  - fonts-conda-ecosystem=1
  - fonttools=4.25.0
  - freetype=2.12.1
  - fribidi=1.0.10
  - future=0.18.3
  - getopt-win32=0.1
  - giflib=5.2.1
  - glib=2.69.1
  - graphite2=1.3.14
  - graphviz=2.50.0
  - gts=0.7.6
  - harfbuzz=4.3.0
  - icc_rt=2022.1.0
  - icu=58.2
  - idna=3.4
  - intel-openmp=2021.4.0
  - joblib=1.2.0
  - jpeg=9e
  - kiwisolver=1.4.4
  - lame=3.100
  - lazy_loader=0.1
  - lcms2=2.12
  - lerc=3.0
  - libboost=1.73.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcurl=7.88.1
  - libdeflate=1.17
  - libffi=3.4.2
  - libflac=1.4.2
  - libgd=2.3.3
  - libiconv=1.16
  - libogg=1.3.4
  - libopus=1.3.1
  - libpng=1.6.39
  - librosa=0.10.0
  - libsndfile=1.2.0
  - libssh2=1.10.0
  - libtiff=4.5.0
  - libvorbis=1.3.7
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libxml2=2.9.14
  - llvmlite=0.39.1
  - lz4-c=1.9.4
  - matplotlib-base=3.7.1
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - mpg123=1.31.3
  - msgpack-python=1.0.5
  - munkres=1.1.4
  - numba=0.56.4
  - numexpr=2.8.4
  - numpy=1.23.5
  - numpy-base=1.23.5
  - openjpeg=2.4.0
  - openssl=1.1.1t
  - packaging=23.0
  - pandas=1.5.2
  - pango=1.50.7
  - pcre=8.45
  - pillow=9.3.0
  - pixman=0.40.0
  - plotly=5.11.0
  - pooch=1.6.0
  - poppler=22.12.0
  - poppler-data=0.4.11
  - pycparser=2.21
  - pydotplus=2.0.2
  - pygments=2.11.2
  - pyopenssl=23.0.0
  - pyparsing=3.0.9
  - pyqt=5.9.2
  - pysocks=1.7.1
  - pysoundfile=0.12.1
  - python=3.10.8
  - python-dateutil=2.8.2
  - python_abi=3.10
  - pytz=2022.7
  - pyyaml=6.0
  - qt=5.9.7
  - requests=2.28.2
  - rich=12.5.1
  - scikit-learn=1.2.1
  - scipy=1.10.0
  - setuptools=65.6.3
  - shellingham=1.5.0
  - sip=4.19.13
  - six=1.16.0
  - soxr=0.1.3
  - soxr-python=0.3.3
  - sqlite=3.41.1
  - tenacity=8.0.1
  - threadpoolctl=3.1.0
  - tk=8.6.12
  - tqdm=4.64.1
  - typer=0.7.0
  - typing_extensions=4.4.0
  - tzdata=2022g
  - ucrt=10.0.22621.0
  - urllib3=1.26.15
  - vc=14.2
  - vs2015_runtime=14.34.31931
  - wheel=0.38.4
  - win_inet_pton=1.1.0
  - wincertstore=0.2
  - xz=5.2.10
  - yaml=0.2.5
  - zlib=1.2.13
  - zstd=1.5.2
  - pip:
      - absl-py==1.4.0
      - astunparse==1.6.3
      - cachetools==5.3.0
      - flatbuffers==23.1.21
      - gast==0.4.0
      - google-auth==2.16.1
      - google-auth-oauthlib==0.4.6
      - google-pasta==0.2.0
      - grpcio==1.51.3
      - h5py==3.8.0
      - keras==2.10.0
      - keras-preprocessing==1.1.2
      - libclang==15.0.6.1
      - markdown==3.4.1
      - markupsafe==2.1.2
      - oauthlib==3.2.2
      - opt-einsum==3.3.0
      - pip==23.0.1
      - protobuf==3.19.6
      - pyasn1==0.4.8
      - pyasn1-modules==0.2.8
      - requests-oauthlib==1.3.1
      - rsa==4.9
      - tensorboard==2.10.1
      - tensorboard-data-server==0.6.1
      - tensorboard-plugin-wit==1.8.1
      - tensorflow==2.10.1
      - tensorflow-estimator==2.10.0
      - tensorflow-io-gcs-filesystem==0.31.0
      - termcolor==2.2.0
      - werkzeug==2.2.3
      - wrapt==1.15.0
